# Generated by Django 3.0.1 on 2019-12-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default='title', max_length=255),
            preserve_default=False,
        ),
    ]
